"""added image_file table

Revision ID: 649eff3a7fc9
Revises: a583aec65d70
Create Date: 2019-12-06 15:17:04.754235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '649eff3a7fc9'
down_revision = 'a583aec65d70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('image_file', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'image_file')
    # ### end Alembic commands ###
